// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ButtonGroupController from "./button_group_controller"
application.register("button-group", ButtonGroupController)

import ChartToolbarController from "./chart_toolbar_controller"
application.register("chart-toolbar", ChartToolbarController)

import ChartTickerListController from "./chart_ticker_list_controller"
application.register("chart-ticker-list", ChartTickerListController)
