class InstrumentSet
  attr :key

  def initialize(key)
    @key = key&.to_sym
  end

  def name = key ? key.to_s.humanize : 'All'
  def symbols = Data[key.to_sym]
  def unprefixed_symbols = symbols.map { |sym| sym.split(':').last }
  def missing_symbols = unprefixed_symbols.reject { |sym| Instrument.exists?(ticker: sym) }
  def instruments = Instrument.where(ticker: unprefixed_symbols)
  alias tickers unprefixed_symbols

  class << self
    def get(key)
      return key if self === key
      all.find { |set| set.key == key.to_sym }
    end

    def null
      new(nil)
    end

    def all
      @all ||= Data.keys.map { |key| new(key) }
    end

    def all_with_null
      [null] + all
    end
  end

  Data = {
    main: %w[
      MOEX:AFKS
      MOEX:AGRO
      MOEX:AMEZ
      MOEX:CHMF
      MOEX:ETLN
      MOEX:EURRUB_TOM
      MOEX:FESH
      MOEX:FIVE
      MOEX:GAZP
      MOEX:GLTR
      MOEX:IMOEX
      MOEX:KRKNP
      MOEX:LNTA
      MOEX:MAGN
      MOEX:MAIL
      MOEX:MTLRP
      MOEX:POGR
      MOEX:POLY
      MOEX:QIWI
      MOEX:ROSN
      MOEX:RSTI
      MOEX:RTSI
      MOEX:RUAL
      MOEX:SBER
      MOEX:SBERP
      MOEX:SIBN
      MOEX:SMLT
      MOEX:SNGSP
      MOEX:TCSG
      MOEX:USDRUB_TOM
      MOEX:VTBR
      MOEX:YNDX
      NASDAQ:AAPL
      NASDAQ:ALTO
      NASDAQ:AMZN
      NASDAQ:ATEX
      NASDAQ:BBBY
      NASDAQ:CERN
      NASDAQ:CHEF
      NASDAQ:CHX
      NASDAQ:DOCU
      NASDAQ:EHTH
      NASDAQ:ETSY
      NASDAQ:FANG
      NASDAQ:FB
      NASDAQ:GOOG
      NASDAQ:GOSS
      NASDAQ:GTHX
      NASDAQ:HRTX
      NASDAQ:INCY
      NASDAQ:INTC
      NASDAQ:METC
      NASDAQ:MOMO
      NASDAQ:MSFT
      NASDAQ:NDX
      NASDAQ:OSUR
      NASDAQ:QDEL
      NASDAQ:QRVO
      NASDAQ:RYTM
      NASDAQ:SND
      NASDAQ:TSLA
      NASDAQ:USAK
      NASDAQ:VEON
      NYSE:AMG
      NYSE:AR
      NYSE:ARCH
      NYSE:AYX
      NYSE:BABA
      NYSE:BG
      NYSE:BTU
      NYSE:C
      NYSE:CCL
      NYSE:CLR
      NYSE:CORR
      NYSE:COTY
      NYSE:DAL
      NYSE:DK
      NYSE:EQT
      NYSE:ET
      NYSE:EURN
      NYSE:FCX
      NYSE:FRO
      NYSE:FTCH
      NYSE:GPS
      NYSE:HCC
      NYSE:HHC
      NYSE:HII
      NYSE:IVZ
      NYSE:KGC
      NYSE:M
      NYSE:MA
      NYSE:MAC
      NYSE:MFGP
      NYSE:NOK
      NYSE:OKE
      NYSE:PBF
      NYSE:RDS.A
      NYSE:RIG
      NYSE:RL
      NYSE:RRC
      NYSE:SPG
      NYSE:SPR
      NYSE:SWN
      NYSE:TEVA
      NYSE:TWTR
      NYSE:V
      NYSE:VALE
      NYSE:X
      NYSE:XOM
      NYSE:XRX
      ICPT
      CHKP
      NLOK
      TLRY
      APEI
      RNFT
    ],
    small: %w[
      AMEX:INS
      AMEX:PTN
      AMEX:UEC
      NASDAQ:AAWW
      NASDAQ:ALTO
      NASDAQ:AMWD
      NASDAQ:ANAB
      NASDAQ:AOSL
      NASDAQ:AOUT
      NASDAQ:APEI
      NASDAQ:APOG
      NASDAQ:AQMS
      NASDAQ:ATEX
      NASDAQ:ATRO
      NASDAQ:AYRO
      NASDAQ:BBSI
      NASDAQ:BGFV
      NASDAQ:BJRI
      NASDAQ:BLNK
      NASDAQ:CCNE
      NASDAQ:CEVA
      NASDAQ:CHEF
      NASDAQ:CLAR
      NASDAQ:CLSK
      NASDAQ:CMCO
      NASDAQ:CNSL
      NASDAQ:CRMT
      NASDAQ:CSWC
      NASDAQ:CSWI
      NASDAQ:CVCO
      NASDAQ:CVGW
      NASDAQ:CZNC
      NASDAQ:DLTH
      NASDAQ:DOMO
      NASDAQ:ECHO
      NASDAQ:ECPG
      NASDAQ:EHTH
      NASDAQ:EPAY
      NASDAQ:EVER
      NASDAQ:FARO
      NASDAQ:FLWS
      NASDAQ:FORR
      NASDAQ:GLNG
      NASDAQ:HCCI
      NASDAQ:HEAR
      NASDAQ:HURN
      NASDAQ:ICBK
      NASDAQ:ICHR
      NASDAQ:IDCC
      NASDAQ:INFN
      NASDAQ:JBSS
      NASDAQ:JOUT
      NASDAQ:KALU
      NASDAQ:KBAL
      NASDAQ:KLXE
      NASDAQ:KRYS
      NASDAQ:LASR
      NASDAQ:LEGH
      NASDAQ:MBUU
      NASDAQ:MCRI
      NASDAQ:METC
      NASDAQ:MTSC
      NASDAQ:MYRG
      NASDAQ:NTGR
      NASDAQ:NVEE
      NASDAQ:NYMT
      NASDAQ:OFIX
      NASDAQ:ORBC
      NASDAQ:OSIS
      NASDAQ:PATK
      NASDAQ:PETQ
      NASDAQ:PI
      NASDAQ:PLUS
      NASDAQ:PNTG
      NASDAQ:PRAA
      NASDAQ:PRFT
      NASDAQ:PRGS
      NASDAQ:PVAC
      NASDAQ:QADA
      NASDAQ:QNST
      NASDAQ:RAVN
      NASDAQ:RRBI
      NASDAQ:RWLK
      NASDAQ:SCSC
      NASDAQ:SGH
      NASDAQ:SNCR
      NASDAQ:SP
      NASDAQ:SPWH
      NASDAQ:STRA
      NASDAQ:STRL
      NASDAQ:SWBI
      NASDAQ:SYKE
      NASDAQ:TLND
      NASDAQ:TPIC
      NASDAQ:TTMI
      NASDAQ:TWNK
      NASDAQ:UCTT
      NASDAQ:UPLD
      NASDAQ:VNOM
      NASDAQ:VRTS
      NASDAQ:VUZI
      NASDAQ:WKHS
      NASDAQ:XONE
      NASDAQ:YORW
      NASDAQ:ZUMZ
      NYSE:AAN
      NYSE:AIR
      NYSE:APRN
      NYSE:ARC
      NYSE:ARCO
      NYSE:ASIX
      NYSE:ATEN
      NYSE:ATGE
      NYSE:AZRE
      NYSE:BOOT
      NYSE:BRBR
      NYSE:BXC
      NYSE:CARS
      NYSE:CIR
      NYSE:CMO
      NYSE:CPK
      NYSE:CPS
      NYSE:CYD
      NYSE:DBD
      NYSE:DHT
      NYSE:DIN
      NYSE:DLX
      NYSE:DNOW
      NYSE:DX
      NYSE:EARN
      NYSE:ENVA
      NYSE:ERJ
      NYSE:FOE
      NYSE:GCO
      NYSE:GES
      NYSE:GTN
      NYSE:HCC
      NYSE:HCHC
      NYSE:HLX
      NYSE:HOME
      NYSE:HSC
      NYSE:HVT
      NYSE:LPG
      NYSE:LRN
      NYSE:MEI
      NYSE:MFA
      NYSE:MHO
      NYSE:MRC
      NYSE:MTRN
      NYSE:NLS
      NYSE:PGTI
      NYSE:PIPR
      NYSE:PLT
      NYSE:PMT
      NYSE:PUMP
      NYSE:QUOT
      NYSE:REX
      NYSE:RGR
      NYSE:RYAM
      NYSE:SLCA
      NYSE:SM
      NYSE:SOL
      NYSE:SRI
      NYSE:STNG
      NYSE:SXI
      NYSE:TDS
      NYSE:TNC
      NYSE:TUP
      NYSE:TWO
      NYSE:UTL
      NYSE:VPG
      NYSE:VRTV
      NYSE:VSTO
    ]
  }
end

__END__

InstrumentSet.new(:main).symbols
